### ISSUE TITLE
Templat Project

### ISSUE THREAD

**Issue by webfolderio** [kracejic/cleanCppProject#11]
Hi,

Could you please add template project support?

Thanks

https://help.github.com/en/articles/creating-a-repository-from-a-template

**Comment by kracejic** [comment]
Hi, 

it is done. 

It looks that right now there is no advance logic in place that would allow us to rename files and replace some strings in the build configuration to customize the executable name via the templates. 

Meanwhile, there is a description on what is needed to customize the project here: https://github.com/kracejic/cleanCppProject/blob/master/doc/start_working.md
